# Generated by Django 3.1.6 on 2023-03-29 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_listing_iamge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='iamge',
            new_name='image',
        ),
    ]
