# Generated by Django 4.1.7 on 2023-03-29 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20230328_1831'),
        ('web', '0007_alter_category_id_alter_complaint_id_and_more'),
    ]

    operations = [
    ]
