# Generated by Django 3.1.6 on 2023-03-29 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_auto_20230326_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
