# Generated by Django 4.1.7 on 2023-03-29 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_alter_conversation_id_alter_conversationmessage_id'),
        ('conversation', '0003_conversation_message'),
    ]

    operations = [
    ]
